### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by imyanice** [apangin/class-file-extractor#3]
Hi! I'm getting this error:
```
└┌(Downloads)┌¨˙java -jar extractor.jar 36920 test.jar
Exception in thread "main" com.sun.tools.attach.AgentLoadException: 100
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:112)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:123)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:151)
	at ClassFileExtractor.main(Unknown Source)
```
The process im trying to extract is Minecraft. Have you any ideas why isn't it working ?
Thanks!

**Comment by apangin** [comment]
Error code 100 means the dynamic attach is disabled in the target JVM, presumably by adding `-XX:+DisableAttachMechanism` JVM option.
